config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root "static_pages#home"
  get "/signup", to:"users#new"
  post "/signup", to: "users#create"
  get "/login", to:"sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to:"sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show, :index] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  # resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, t("home.home")) %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= link_to t("micropost.micropost_feed"), microposts_path %></h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
   <h1>トライアルアプリケーション</h1>

  <h1><%= t "home.ruby_on_rails_trail_app" %></h1>
  <h2>
    <%= t "home.this_is_the_home_page" %>
    <a href="https://www.railstutorial.org/"><%= t "home.ruby_on_rails_tutorial" %></a>
    <%= t "home.sample_application" %>
  </h2>
  <%= link_to t("home.signup"), signup_path, class: "btn btn-lg btn-primary" %>

  </div>
  <!-- <img alt=t("home.rails_logo") src="/assets/rails.png" /> -->
<% end %>