config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root "static_pages#home"
  get "/signup", to:"users#new"
  post "/signup", to: "users#create"
  get "/login", to:"sessions#new"
  post "/login", to:"sessions#create"
  delete "/logout", to:"sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show, :index] do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  # resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: Settings.micropost.title_length}
  validates :content, presence: true, length: {maximum: Settings.micropost.content_length}
  validate :picture_size

  private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > Settings.micropost.picture_size.megabytes
      errors.add(:picture, "picture_should_be_less")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  before_action :set_micropost, only: :show
  
  def index
    @microposts = Micropost.paginate(page: params[:page])
  end

  def show
    @comment = @micropost.comments.build
    @comments = @micropost.comments.includes(:user)
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = t "micropost.micropost_created"
      redirect_to root_url
    else
      @feed_items = []
      render "static_pages/home"
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = t "micropost.micropost_deleted"
    redirect_to request.referrer || root_url
  end

  private
  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

  def set_micropost
    @micropost = Micropost.find(params[:id])
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.user.avatar_size), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span><hr><hr>
  <span class="title"><%= link_to micropost.title, micropost %></span>
  <span class="content"><%= micropost.content %></span>
  <%= image_tag micropost.picture.url if micropost.picture? %>
  <span class="timestamp">
    <%= t "micropost.posted" %><%= time_ago_in_words(micropost.created_at) %><%= t "micropost.ago" %>
    <% if current_user?(micropost.user) %>
      <%= link_to t("micropost.delete"), micropost, method: :delete, data: {confirm: t("micropost.you_sure")} %>
    <% end %>
  </span>
</li>

app/views/microposts/index.html.erb
<h1><%= t "micropost.all_entries" %></h1>
<% @microposts.each do |micropost| %>
  <div class="post">
    <h1 style="text-align: left">
      <%= link_to micropost.title, micropost %>
    </h1>
    <p class="lead">
       <%= t "micropost.by" %><%= link_to micropost.user.name, micropost.user %>
    </p>
    <p>
      <span class="glyphicon glyphicon-time"></span>
      <%= t "micropost.posted" %><%= time_ago_in_words(micropost.created_at) %><%= t "micropost.ago" %>
      <!-- <p><%= micropost.content %></p> -->
      <span class="content">
        <p class="lead"><%= micropost.content %></p>
        <%= image_tag micropost.picture.url if micropost.picture? %>
      </span>
      <hr>
      <%= link_to t("micropost.read_more"), micropost, class: "btn btn-primary" %>
      <hr>
    </p>
  </div>
<% end %>
<%= will_paginate %>

app/views/microposts/show.html.erb
<div class="row">
  <div class="col-lg-8">
    <h1 style="text-align: left"><%= @micropost.title %></h1>
    <p class="lead">
      <%= t "micropost.by" %><%= link_to @micropost.user.name, @micropost.user %>
    </p>
    <hr>
    <p>
      <span class="glyphicon glyphicon-time"></span>
      <%= t "micropost.posted" %>
      <%= time_ago_in_words(@micropost.created_at) %>
      <%= t "micropost.ago" %>
    </p>
    <hr>
    <span class="content">
      <p class="lead"><%= @micropost.content %></p>
      <%= image_tag @micropost.picture.url if @micropost.picture? %>
    </span>
    <hr>
    <span class="like">
      <%= render "likes/like_form", micropost: @micropost %>
    </span>
    <div class="well" id="well">
      <h4><%= t "micropost.leave_comment" %></h4>
      <%= form_for @comment, :url => micropost_comments_path(@micropost) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <%= f.text_area :content, placeholder: t("micropost.compose_new_comment"), class: "form-control" %>
        <%= f.submit t("micropost.submit"), class: "btn btn-primary" %>
      <% end %>
    </div>
    <hr>
    <% @comments.each do |comment| %>
      <div class="media">
        <%= link_to gravatar_for(comment.user, size: 30), comment.user, class: "pull-left" %>
        <div class="media-body">
          <h4 class="media-heading"><%= link_to comment.user.name, comment.user %>
            <small><%= comment.created_at %></small>
          </h4>
          <%= comment.content %>
          <% if current_user.current_user?(comment.user) %>
            <%= link_to edit_micropost_comment_path(micropost, comment), remote: true do %>
              <i class="fa fa-pencil-square-o"></i>
              edit
            <% end %>
            <%= link_to micropost_comment_path(micropost, comment), method: :delete, remote: true do %>
              <i class="fa fa-trash-o"></i>
              delete
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>